location = /jbrowser {
    absolute_redirect off;
    return 308 /jbrowser/;
}

location ^~ /jbrowser/ {
    alias /srv/jbrowser/site/;
    index index.html;
    expires -1;
}

location ^~ /jbrowser/static/ {
    alias /srv/jbrowser/site/static/;
    expires -1;
}

location ^~ /jbrowser/app/static/ {
    alias /srv/jbrowser/app/static/;
    expires 1y;
}

location ^~ /jbrowser/app/ {
    alias /srv/jbrowser/app/;
    index index.html;
    absolute_redirect off;
    expires -1;
}

location ^~ /jbrowser/bundles/ {
    alias /data/bundles/;
    autoindex on;
    autoindex_format json;
    autoindex_localtime off;
    absolute_redirect off;
    charset utf-8;
    gzip off;
}
