[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:primer3plus-api]
command=python3 /primer3plus/server/server.py
autostart=true
autorestart=true
stdout_logfile=/var/log/primer3plus-api.log
stderr_logfile=/var/log/primer3plus-api-err.log

[program:primer3plus-frontend]
command=python3 -m http.server 1234 --directory /primer3plus/client/dist
autostart=true
autorestart=true
stdout_logfile=/var/log/primer3plus-frontend.log
stderr_logfile=/var/log/primer3plus-frontend-err.log
